const errorCodes = Object.freeze([
    "SUCCESS",
    "UNAUTHORIZED",
    "MISSING_QUERY_PARAMETER",
    "ID_NOT_FOUND",
    "USER_NOT_FOUND",
    "INFUFFICIENT_POINTS",
    "OUT_OF_STOCK",
    "INTERNAL_ERROR",
    "WRONG_DATA",
    "ALL_ANSWERED",
    "MISSING_QUESTION",
    "NO_MATCHING_REPORT_ID",
    "ALREADY_RESOLVED_REPORT",
    "BANNED",
    "MISSING_TOKEN",
    "INVALID_TOKEN",
    "AUTHENTICATED_USER_EMAIL_NOT_FOUND",
    "AUTHENTICATED_USER_BANNED",
    "REGISTRATING_USER_DUPLICATED_REQUEST",
    "EMAIL_ALREADY_REGISTERED",
    "REGISTRATING_USER_INVALID_PASSWORD",
    "INVALID_REGISTRATION_REQUEST",
    "REGISTRATION_CODE_EXPIRED",
    "REGISTRATION_CODE_INVALID",
    "COORDINATES_CHOOSEN_NOT_VALID",
    "MISSING_QUESTION_OPTIONS",
    "NO_MATCHING_AUTHENTICATED_USER_ID",
    "WRONG_PASSWORD",
    "NOT_FOUND",
    "EMAIL_CHOSEN_NOT_VALID"
]);

const getError = (errorToSearch) => ({code: errorCodes.indexOf(errorToSearch), message: errorToSearch});

module.exports = getError;